"""
pdf_report.py — PDF clinical report generator for Anatom AI.

Produces a structured, print-ready PDF containing:
  - Cover page with branding, subject ID, and scan date
  - Executive summary (RANO category, total tumour burden)
  - Sub-region volumetric breakdown table (NCR / ED / ET / WT / TC / ET)
  - Optional longitudinal comparison section (ΔV, growth rates, RANO timeline)
  - Standard clinical disclaimer footer

Usage
-----
    from src.reporting.pdf_report import PDFReportBuilder, ReportConfig
    from src.analytics.volumetrics import VolumetricResult

    cfg = ReportConfig(subject_id="BraTS-001", scan_date="2026-04-13")
    builder = PDFReportBuilder(cfg)
    pdf_bytes = builder.build(result_t2=vol_result, longitudinal_report=long_report)
    with open("report.pdf", "wb") as f:
        f.write(pdf_bytes)
"""

from __future__ import annotations

import io
from dataclasses import dataclass, field
from datetime import date
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from src.analytics.volumetrics import VolumetricResult
from src.analytics.longitudinal import LongitudinalReport
from typing import Dict

# Colour palette
_NAVY = colors.HexColor("#0D2137")
_CYAN = colors.HexColor("#4FC3F7")
_DARK_BG = colors.HexColor("#1A1A2E")
_LIGHT_GRAY = colors.HexColor("#E0E0E0")
_RED = colors.HexColor("#EF5350")
_GREEN = colors.HexColor("#66BB6A")
_YELLOW = colors.HexColor("#FFA726")
_BLUE = colors.HexColor("#42A5F5")

_RANO_COLOUR = {"CR": _GREEN, "PR": _BLUE, "SD": _YELLOW, "PD": _RED}


@dataclass
class ReportConfig:
    """Configuration for the PDF report."""
    subject_id: str = "Unknown"
    scan_date: str = field(default_factory=lambda: str(date.today()))
    institution: str = "Anatom AI Clinical Analytics"
    modality: str = "MRI — BraTS Multi-Modal"
    radiologist: str = "AI-Assisted Analysis"
    disclaimer: str = (
        "This report was generated by Anatom AI, an AI-assisted research tool. "
        "It is intended for investigational use only and does not constitute a "
        "medical diagnosis. All findings must be reviewed and validated by a "
        "qualified radiologist before clinical use."
    )


class PDFReportBuilder:
    """
    Build a branded PDF clinical report from analytics results.

    Parameters
    ----------
    config : ReportConfig — subject metadata and branding options.
    """

    def __init__(self, config: ReportConfig) -> None:
        self.config = config
        self._styles = self._build_styles()

    # ------------------------------------------------------------------ build
    def build(
        self,
        result: VolumetricResult,
        longitudinal_report: Optional[LongitudinalReport] = None,
        radiomic_features: Optional[Dict[str, Dict[str, float]]] = None,
        narrative_text: Optional[str] = None,
        risk_estimate=None,
    ) -> bytes:
        """
        Assemble the full PDF and return it as bytes.

        Parameters
        ----------
        result              : VolumetricResult from the most recent scan.
        longitudinal_report : optional LongitudinalReport for growth tracking.
        radiomic_features   : optional dict from RadiomicsExtractor.extract().
        narrative_text      : optional pre-rendered AI narrative string.
        risk_estimate       : optional RiskEstimate for recurrence risk section.

        Returns
        -------
        bytes — the complete PDF file content.
        """
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=A4,
            leftMargin=2 * cm,
            rightMargin=2 * cm,
            topMargin=2.5 * cm,
            bottomMargin=2.5 * cm,
            title=f"Anatom AI Report — {self.config.subject_id}",
            author=self.config.institution,
        )

        story = []
        story += self._cover_section()
        story += self._patient_info_section()
        story += self._executive_summary(result, longitudinal_report)
        story += self._volumetric_table(result)
        if longitudinal_report is not None:
            story += self._longitudinal_section(longitudinal_report)
        if radiomic_features is not None:
            story += self._radiomics_section(radiomic_features)
        if risk_estimate is not None:
            story += self._risk_section(risk_estimate)
        if narrative_text:
            story += self._narrative_section(narrative_text)
        story += self._disclaimer_section()

        doc.build(story, onFirstPage=self._page_header_footer,
                  onLaterPages=self._page_header_footer)
        return buf.getvalue()

    # ---------------------------------------------------------------- sections
    def _cover_section(self) -> list:
        s = self._styles
        return [
            Spacer(1, 1.5 * cm),
            Paragraph("🧠 Anatom AI", s["title"]),
            Paragraph("3D Brain Tumour Segmentation &amp; Volumetric Analysis", s["subtitle"]),
            HRFlowable(width="100%", thickness=2, color=_CYAN, spaceAfter=0.4 * cm),
            Paragraph("CLINICAL ANALYSIS REPORT", s["report_label"]),
            Spacer(1, 0.8 * cm),
        ]

    def _patient_info_section(self) -> list:
        s = self._styles
        cfg = self.config
        data = [
            ["Subject ID",   cfg.subject_id,   "Institution", cfg.institution],
            ["Scan Date",    cfg.scan_date,     "Modality",    cfg.modality],
            ["Analyst",      cfg.radiologist,   "Report Date", str(date.today())],
        ]
        tbl = Table(data, colWidths=[3.5 * cm, 6.5 * cm, 3.5 * cm, 5.5 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (0, -1), _DARK_BG),
            ("BACKGROUND",  (2, 0), (2, -1), _DARK_BG),
            ("TEXTCOLOR",   (0, 0), (-1, -1), colors.white),
            ("TEXTCOLOR",   (0, 0), (0, -1), _CYAN),
            ("TEXTCOLOR",   (2, 0), (2, -1), _CYAN),
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME",    (2, 0), (2, -1), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#1a1a2e"), colors.HexColor("#0f0f19")]),
            ("BOX",         (0, 0), (-1, -1), 0.5, _CYAN),
            ("INNERGRID",   (0, 0), (-1, -1), 0.25, colors.HexColor("#333355")),
            ("PADDING",     (0, 0), (-1, -1), 5),
        ]))
        return [tbl, Spacer(1, 0.6 * cm)]

    def _executive_summary(
        self,
        result: VolumetricResult,
        long_report: Optional[LongitudinalReport],
    ) -> list:
        s = self._styles
        items = [
            Paragraph("Executive Summary", s["section_header"]),
            HRFlowable(width="100%", thickness=0.5, color=_CYAN, spaceAfter=0.2 * cm),
        ]

        rano_text = "N/A"
        rano_col = colors.white
        if long_report is not None:
            rano_text = long_report.rano_category
            rano_col = _RANO_COLOUR.get(rano_text, colors.white)

        summary_data = [
            ["Metric", "Value"],
            ["Whole Tumour Volume (WT)", f"{result.wt_mm3:,.1f} mm³"],
            ["Tumour Core Volume (TC)",  f"{result.tc_mm3:,.1f} mm³"],
            ["Enhancing Tumour (ET)",    f"{result.et_mm3:,.1f} mm³"],
            ["RANO Response Category",   rano_text],
        ]

        tbl = Table(summary_data, colWidths=[9 * cm, 9 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), _NAVY),
            ("TEXTCOLOR",     (0, 0), (-1, 0), _CYAN),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 10),
            ("BACKGROUND",    (0, 1), (-1, -1), colors.HexColor("#0f0f19")),
            ("TEXTCOLOR",     (0, 1), (-1, -1), colors.white),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1),
             [colors.HexColor("#1a1a2e"), colors.HexColor("#0f0f19")]),
            ("BOX",           (0, 0), (-1, -1), 0.5, _CYAN),
            ("INNERGRID",     (0, 0), (-1, -1), 0.25, colors.HexColor("#333355")),
            ("PADDING",       (0, 0), (-1, -1), 6),
            ("ALIGN",         (1, 0), (-1, -1), "RIGHT"),
        ]))
        items += [tbl, Spacer(1, 0.6 * cm)]
        return items

    def _volumetric_table(self, result: VolumetricResult) -> list:
        s = self._styles
        items = [
            Paragraph("Sub-Region Volumetric Breakdown", s["section_header"]),
            HRFlowable(width="100%", thickness=0.5, color=_CYAN, spaceAfter=0.2 * cm),
        ]

        rows = [["Region", "Label", "Volume (mm³)", "Brain Fraction (%)"]]
        region_info = [
            ("Necrotic Core",           "NCR", "NCR",  1),
            ("Peritumoral Edema",        "ED",  "ED",   2),
            ("Gadolinium-Enhancing",     "ET",  "ET",   3),
            ("Whole Tumour (WT=1+2+3)", "WT",  None,  None),
            ("Tumour Core  (TC=1+3)",   "TC",  None,  None),
        ]
        for long_name, short_name, vol_key, _ in region_info:
            if vol_key in ("NCR", "ED", "ET"):
                vol = result.volumes_mm3.get(vol_key, 0.0)
            elif short_name == "WT":
                vol = result.wt_mm3
            else:
                vol = result.tc_mm3
            frac = result.fractions.get(short_name, result.fractions.get(vol_key, 0.0))
            rows.append([long_name, short_name, f"{vol:,.1f}", f"{frac * 100:.2f}"])

        tbl = Table(rows, colWidths=[7 * cm, 2.5 * cm, 4 * cm, 4.5 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), _NAVY),
            ("TEXTCOLOR",     (0, 0), (-1, 0), _CYAN),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("BACKGROUND",    (0, 1), (-1, -1), colors.HexColor("#0f0f19")),
            ("TEXTCOLOR",     (0, 1), (-1, -1), colors.white),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1),
             [colors.HexColor("#1a1a2e"), colors.HexColor("#0f0f19")]),
            ("BOX",           (0, 0), (-1, -1), 0.5, _CYAN),
            ("INNERGRID",     (0, 0), (-1, -1), 0.25, colors.HexColor("#333355")),
            ("PADDING",       (0, 0), (-1, -1), 5),
            ("ALIGN",         (2, 1), (-1, -1), "RIGHT"),
        ]))
        items += [tbl, Spacer(1, 0.6 * cm)]
        return items

    def _longitudinal_section(self, report: LongitudinalReport) -> list:
        s = self._styles
        items = [
            Paragraph("Longitudinal Growth Analysis", s["section_header"]),
            HRFlowable(width="100%", thickness=0.5, color=_CYAN, spaceAfter=0.2 * cm),
        ]

        rows = [["Region", "Baseline (mm³)", "Follow-up (mm³)", "Δ (mm³)", "Rate (mm³/day)", "Change (%)"]]
        for region in ("WT", "TC", "ET"):
            rows.append([
                region,
                f"{report.volumes_t1.get(region, 0):,.1f}",
                f"{report.volumes_t2.get(region, 0):,.1f}",
                f"{report.delta_mm3.get(region, 0):+,.1f}",
                f"{report.rate_mm3_per_day.get(region, 0):+.2f}",
                f"{report.pct_change.get(region, 0):+.1f}%",
            ])

        tbl = Table(rows, colWidths=[2 * cm, 3 * cm, 3.5 * cm, 3 * cm, 3.5 * cm, 3 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), _NAVY),
            ("TEXTCOLOR",     (0, 0), (-1, 0), _CYAN),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("BACKGROUND",    (0, 1), (-1, -1), colors.HexColor("#0f0f19")),
            ("TEXTCOLOR",     (0, 1), (-1, -1), colors.white),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1),
             [colors.HexColor("#1a1a2e"), colors.HexColor("#0f0f19")]),
            ("BOX",           (0, 0), (-1, -1), 0.5, _CYAN),
            ("INNERGRID",     (0, 0), (-1, -1), 0.25, colors.HexColor("#333355")),
            ("PADDING",       (0, 0), (-1, -1), 5),
            ("ALIGN",         (1, 1), (-1, -1), "RIGHT"),
        ]))

        rano_col = _RANO_COLOUR.get(report.rano_category, colors.white)
        items += [
            tbl, Spacer(1, 0.3 * cm),
            Paragraph(
                f"Interval: {report.days_elapsed:.0f} days  |  "
                f"RANO Classification: <b>{report.rano_category}</b>  |  "
                f"WT change: {report.rano_pct_change:+.1f}%",
                s["body"],
            ),
            Spacer(1, 0.6 * cm),
        ]
        return items

    def _radiomics_section(self, features: Dict[str, Dict[str, float]]) -> list:
        """Radiomic feature table per BraTS sub-region."""
        s = self._styles
        items = [
            Paragraph("Radiomic Feature Analysis", s["section_header"]),
            HRFlowable(width="100%", thickness=0.5, color=_CYAN, spaceAfter=0.2 * cm),
        ]

        # Build one table per region that has non-zero features
        for region in ("ET", "NCR", "ED", "WT", "TC"):
            feats = features.get(region, {})
            if not feats or feats.get("mesh_volume_mm3", 0) == 0:
                continue

            items.append(Paragraph(f"Region: {region}", s["body"]))
            rows = [["Feature", "Value"]]
            display = {
                "mesh_volume_mm3":        ("Volume (mm³)",           f"{feats.get('mesh_volume_mm3', 0):,.1f}"),
                "sphericity":             ("Sphericity",              f"{feats.get('sphericity', 0):.4f}"),
                "surface_area_to_volume": ("Surface/Volume Ratio",    f"{feats.get('surface_area_to_volume', 0):.4f}"),
                "elongation":             ("Elongation",              f"{feats.get('elongation', 0):.4f}"),
                "compactness":            ("Compactness",             f"{feats.get('compactness', 0):.4f}"),
                "mean_intensity":         ("Mean Intensity",          f"{feats.get('mean_intensity', 0):.2f}"),
                "entropy":                ("Intensity Entropy (bits)", f"{feats.get('entropy', 0):.4f}"),
                "kurtosis":               ("Kurtosis",                f"{feats.get('kurtosis', 0):.4f}"),
                "glcm_contrast":          ("GLCM Contrast",           f"{feats.get('glcm_contrast', 0):.4f}"),
                "glcm_homogeneity":       ("GLCM Homogeneity",        f"{feats.get('glcm_homogeneity', 0):.4f}"),
            }
            for _, (label, val) in display.items():
                rows.append([label, val])

            tbl = Table(rows, colWidths=[9 * cm, 9 * cm])
            tbl.setStyle(TableStyle([
                ("BACKGROUND",  (0, 0), (-1, 0), _NAVY),
                ("TEXTCOLOR",   (0, 0), (-1, 0), _CYAN),
                ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE",    (0, 0), (-1, -1), 8),
                ("BACKGROUND",  (0, 1), (-1, -1), colors.HexColor("#0f0f19")),
                ("TEXTCOLOR",   (0, 1), (-1, -1), colors.white),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                 [colors.HexColor("#1a1a2e"), colors.HexColor("#0f0f19")]),
                ("BOX",         (0, 0), (-1, -1), 0.5, _CYAN),
                ("INNERGRID",   (0, 0), (-1, -1), 0.25, colors.HexColor("#333355")),
                ("PADDING",     (0, 0), (-1, -1), 4),
                ("ALIGN",       (1, 1), (-1, -1), "RIGHT"),
            ]))
            items += [tbl, Spacer(1, 0.3 * cm)]

        return items + [Spacer(1, 0.3 * cm)]

    def _risk_section(self, risk_estimate) -> list:
        """Recurrence risk score section."""
        s = self._styles
        score = risk_estimate.score
        interp = risk_estimate.interpretation
        risk_color = {
            "Low":       _GREEN,
            "Moderate":  _YELLOW,
            "High":      colors.HexColor("#FF6B35"),
            "Very High": _RED,
        }.get(interp, colors.white)

        items = [
            Paragraph("Recurrence Risk Assessment", s["section_header"]),
            HRFlowable(width="100%", thickness=0.5, color=_CYAN, spaceAfter=0.2 * cm),
        ]

        summary_data = [
            ["Risk Score", f"{score}/100"],
            ["Interpretation", interp],
        ]
        tbl = Table(summary_data, colWidths=[9 * cm, 9 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (0, -1), _NAVY),
            ("TEXTCOLOR",   (0, 0), (0, -1), _CYAN),
            ("TEXTCOLOR",   (1, 0), (1, -1), colors.white),
            ("TEXTCOLOR",   (1, 1), (1, 1), risk_color),
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 10),
            ("BACKGROUND",  (1, 0), (1, -1), colors.HexColor("#0f0f19")),
            ("BOX",         (0, 0), (-1, -1), 0.5, _CYAN),
            ("INNERGRID",   (0, 0), (-1, -1), 0.25, colors.HexColor("#333355")),
            ("PADDING",     (0, 0), (-1, -1), 6),
        ]))
        items += [tbl, Spacer(1, 0.2 * cm)]

        if risk_estimate.top_factors:
            items.append(Paragraph("Primary contributing factors:", s["body"]))
            for factor in risk_estimate.top_factors:
                items.append(Paragraph(f"• {factor}", s["body"]))

        items += [
            Spacer(1, 0.2 * cm),
            Paragraph(
                "⚠ RESEARCH PROTOTYPE — Not validated for clinical decision-making.",
                s["disclaimer"],
            ),
            Spacer(1, 0.4 * cm),
        ]
        return items

    def _narrative_section(self, narrative_text: str) -> list:
        """AI clinical impression section rendered from narrative text."""
        from reportlab.platypus import Preformatted

        s = self._styles
        mono_style = ParagraphStyle(
            "mono", fontSize=7, textColor=colors.HexColor("#B0C8D8"),
            fontName="Courier", spaceAfter=2, leading=11,
            backColor=colors.HexColor("#070f1e"),
        )
        items = [
            Paragraph("AI Clinical Impression", s["section_header"]),
            HRFlowable(width="100%", thickness=0.5, color=_CYAN, spaceAfter=0.2 * cm),
            Preformatted(narrative_text, mono_style),
            Spacer(1, 0.4 * cm),
        ]
        return items

    def _disclaimer_section(self) -> list:
        s = self._styles
        return [
            HRFlowable(width="100%", thickness=0.5, color=colors.gray),
            Spacer(1, 0.2 * cm),
            Paragraph("Clinical Disclaimer", s["disclaimer_header"]),
            Paragraph(self.config.disclaimer, s["disclaimer"]),
        ]

    # --------------------------------------------------------- page decorators
    def _page_header_footer(self, canvas, doc) -> None:
        canvas.saveState()
        W, H = A4
        # Header bar
        canvas.setFillColor(_NAVY)
        canvas.rect(0, H - 1.5 * cm, W, 1.5 * cm, fill=True, stroke=False)
        canvas.setFillColor(_CYAN)
        canvas.setFont("Helvetica-Bold", 10)
        canvas.drawString(2 * cm, H - 1.0 * cm, "Anatom AI — Clinical Analysis Report")
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.white)
        canvas.drawRightString(W - 2 * cm, H - 1.0 * cm,
                               f"Subject: {self.config.subject_id}  |  {self.config.scan_date}")
        # Footer
        canvas.setFillColor(_NAVY)
        canvas.rect(0, 0, W, 1.0 * cm, fill=True, stroke=False)
        canvas.setFillColor(colors.gray)
        canvas.setFont("Helvetica", 7)
        canvas.drawString(2 * cm, 0.35 * cm, self.config.institution)
        canvas.drawRightString(W - 2 * cm, 0.35 * cm, f"Page {doc.page}")
        canvas.restoreState()

    # ----------------------------------------------------------------- styles
    def _build_styles(self) -> dict:
        base = getSampleStyleSheet()
        return {
            "title": ParagraphStyle(
                "title", fontSize=26, textColor=_CYAN, alignment=TA_CENTER,
                fontName="Helvetica-Bold", spaceAfter=4,
            ),
            "subtitle": ParagraphStyle(
                "subtitle", fontSize=12, textColor=_LIGHT_GRAY, alignment=TA_CENTER,
                fontName="Helvetica", spaceAfter=10,
            ),
            "report_label": ParagraphStyle(
                "report_label", fontSize=10, textColor=colors.white, alignment=TA_CENTER,
                fontName="Helvetica-Bold", spaceAfter=8,
                backColor=_DARK_BG, borderPadding=6,
            ),
            "section_header": ParagraphStyle(
                "section_header", fontSize=13, textColor=_CYAN,
                fontName="Helvetica-Bold", spaceBefore=12, spaceAfter=4,
            ),
            "body": ParagraphStyle(
                "body", fontSize=9, textColor=colors.white,
                fontName="Helvetica", spaceAfter=4,
            ),
            "disclaimer_header": ParagraphStyle(
                "disclaimer_header", fontSize=9, textColor=colors.gray,
                fontName="Helvetica-Bold", spaceBefore=4, spaceAfter=2,
            ),
            "disclaimer": ParagraphStyle(
                "disclaimer", fontSize=7, textColor=colors.gray,
                fontName="Helvetica", spaceAfter=4,
            ),
        }
