"""Seed 30 realistic Delhi/NCR doctors into the doctors table."""
from __future__ import annotations

import json
import uuid

DOCTORS_SEED: list[dict] = [
    {
        "id": "doc-001",
        "name": "Dr. Arjun Mehta",
        "specialization": "Neurologist",
        "subspecialties": ["Epilepsy", "Headache Disorders", "Stroke"],
        "experience_years": 16,
        "rating": 4.8,
        "review_count": 312,
        "consultation_fee": 1200,
        "mode": "both",
        "hospital": "Apollo Hospital, Sarita Vihar",
        "city": "Delhi",
        "latitude": 28.5355,
        "longitude": 77.2990,
        "verified": True,
        "degrees": ["MBBS", "MD Neurology", "DM Neurology"],
        "languages": ["Hindi", "English"],
        "about": "Senior neurologist with 16+ years specialising in epilepsy, migraine, and cerebrovascular disorders. Trained at AIIMS Delhi.",
        "availability": {"mon": ["10:00", "11:00", "14:00"], "wed": ["10:00", "11:00"], "fri": ["14:00", "15:00", "16:00"]},
    },
    {
        "id": "doc-002",
        "name": "Dr. Priya Sharma",
        "specialization": "Cardiologist",
        "subspecialties": ["Interventional Cardiology", "Heart Failure", "Echocardiography"],
        "experience_years": 14,
        "rating": 4.9,
        "review_count": 445,
        "consultation_fee": 1500,
        "mode": "both",
        "hospital": "Max Super Speciality Hospital, Saket",
        "city": "Delhi",
        "latitude": 28.5244,
        "longitude": 77.2066,
        "verified": True,
        "degrees": ["MBBS", "MD Medicine", "DM Cardiology", "FESC"],
        "languages": ["Hindi", "English", "Punjabi"],
        "about": "Leading interventional cardiologist, performed 2000+ angioplasties. Expert in structural heart disease.",
        "availability": {"tue": ["09:00", "10:00", "11:00"], "thu": ["09:00", "10:00"], "sat": ["10:00", "11:00", "12:00"]},
    },
    {
        "id": "doc-003",
        "name": "Dr. Rajiv Gupta",
        "specialization": "Orthopedist",
        "subspecialties": ["Joint Replacement", "Sports Medicine", "Spine Surgery"],
        "experience_years": 20,
        "rating": 4.7,
        "review_count": 523,
        "consultation_fee": 1000,
        "mode": "offline",
        "hospital": "Fortis Hospital, Vasant Kunj",
        "city": "Delhi",
        "latitude": 28.5298,
        "longitude": 77.1588,
        "verified": True,
        "degrees": ["MBBS", "MS Orthopaedics", "Fellowship Joint Replacement"],
        "languages": ["Hindi", "English"],
        "about": "Expert in knee and hip replacement surgeries with 20 years experience. Trained at HSS New York.",
        "availability": {"mon": ["08:00", "09:00", "10:00"], "wed": ["08:00", "09:00"], "fri": ["08:00", "09:00", "10:00"]},
    },
    {
        "id": "doc-004",
        "name": "Dr. Sunita Kapoor",
        "specialization": "Dermatologist",
        "subspecialties": ["Cosmetic Dermatology", "Psoriasis", "Hair Disorders"],
        "experience_years": 12,
        "rating": 4.6,
        "review_count": 289,
        "consultation_fee": 800,
        "mode": "both",
        "hospital": "Skin & You Clinic, South Extension",
        "city": "Delhi",
        "latitude": 28.5693,
        "longitude": 77.2228,
        "verified": True,
        "degrees": ["MBBS", "MD Dermatology", "DNB"],
        "languages": ["Hindi", "English"],
        "about": "Specialist in medical and cosmetic dermatology, treating complex skin conditions and hair loss.",
        "availability": {"mon": ["12:00", "13:00", "17:00"], "thu": ["12:00", "13:00"], "sat": ["10:00", "11:00"]},
    },
    {
        "id": "doc-005",
        "name": "Dr. Vikram Singh",
        "specialization": "Gastroenterologist",
        "subspecialties": ["Liver Disease", "IBD", "Endoscopy"],
        "experience_years": 15,
        "rating": 4.8,
        "review_count": 376,
        "consultation_fee": 1100,
        "mode": "both",
        "hospital": "Sir Ganga Ram Hospital, Rajinder Nagar",
        "city": "Delhi",
        "latitude": 28.6448,
        "longitude": 77.1855,
        "verified": True,
        "degrees": ["MBBS", "MD Gastroenterology", "DM", "MRCP"],
        "languages": ["Hindi", "English"],
        "about": "Gastroenterologist with expertise in advanced endoscopy and liver disease management.",
        "availability": {"tue": ["11:00", "12:00", "15:00"], "thu": ["11:00", "12:00"], "sat": ["09:00", "10:00"]},
    },
    {
        "id": "doc-006",
        "name": "Dr. Ananya Bose",
        "specialization": "Psychiatrist",
        "subspecialties": ["Depression", "Anxiety Disorders", "Addiction Medicine"],
        "experience_years": 10,
        "rating": 4.9,
        "review_count": 198,
        "consultation_fee": 1500,
        "mode": "both",
        "hospital": "NIMHANS Affiliated Centre, Lajpat Nagar",
        "city": "Delhi",
        "latitude": 28.5672,
        "longitude": 77.2431,
        "verified": True,
        "degrees": ["MBBS", "MD Psychiatry", "FIPS"],
        "languages": ["Hindi", "English", "Bengali"],
        "about": "Compassionate psychiatrist focused on evidence-based treatment of mood disorders and anxiety.",
        "availability": {"mon": ["16:00", "17:00", "18:00"], "wed": ["16:00", "17:00"], "fri": ["16:00", "17:00"]},
    },
    {
        "id": "doc-007",
        "name": "Dr. Rohit Verma",
        "specialization": "Pulmonologist",
        "subspecialties": ["Asthma", "COPD", "Sleep Apnea"],
        "experience_years": 13,
        "rating": 4.7,
        "review_count": 267,
        "consultation_fee": 900,
        "mode": "both",
        "hospital": "BLK-Max Super Speciality, Pusa Road",
        "city": "Delhi",
        "latitude": 28.6435,
        "longitude": 77.1672,
        "verified": True,
        "degrees": ["MBBS", "MD Pulmonology", "DNB"],
        "languages": ["Hindi", "English"],
        "about": "Respiratory medicine specialist with focus on chronic lung diseases, allergy, and sleep disorders.",
        "availability": {"mon": ["09:00", "10:00", "11:00"], "thu": ["09:00", "10:00"], "sat": ["11:00", "12:00"]},
    },
    {
        "id": "doc-008",
        "name": "Dr. Neeraj Agarwal",
        "specialization": "Endocrinologist",
        "subspecialties": ["Diabetes", "Thyroid Disorders", "Obesity"],
        "experience_years": 18,
        "rating": 4.8,
        "review_count": 421,
        "consultation_fee": 1300,
        "mode": "both",
        "hospital": "Indraprastha Apollo, Jasola",
        "city": "Delhi",
        "latitude": 28.5436,
        "longitude": 77.2967,
        "verified": True,
        "degrees": ["MBBS", "MD Endocrinology", "FACE"],
        "languages": ["Hindi", "English"],
        "about": "Senior endocrinologist managing complex diabetes, thyroid diseases, and metabolic disorders.",
        "availability": {"tue": ["10:00", "11:00", "12:00"], "fri": ["10:00", "11:00"], "sat": ["09:00", "10:00", "11:00"]},
    },
    {
        "id": "doc-009",
        "name": "Dr. Meera Joshi",
        "specialization": "Ophthalmologist",
        "subspecialties": ["Cataract Surgery", "Glaucoma", "Retina"],
        "experience_years": 14,
        "rating": 4.8,
        "review_count": 334,
        "consultation_fee": 700,
        "mode": "offline",
        "hospital": "Centre for Sight, Safdarjung",
        "city": "Delhi",
        "latitude": 28.5677,
        "longitude": 77.2033,
        "verified": True,
        "degrees": ["MBBS", "MS Ophthalmology", "FRCS"],
        "languages": ["Hindi", "English"],
        "about": "Eye surgeon specialising in phacoemulsification cataract surgery and glaucoma management.",
        "availability": {"mon": ["08:00", "09:00", "10:00"], "wed": ["08:00", "09:00"], "fri": ["08:00", "09:00"]},
    },
    {
        "id": "doc-010",
        "name": "Dr. Suresh Bansal",
        "specialization": "ENT Specialist",
        "subspecialties": ["Sinus Surgery", "Hearing Loss", "Head & Neck Oncology"],
        "experience_years": 22,
        "rating": 4.6,
        "review_count": 289,
        "consultation_fee": 800,
        "mode": "both",
        "hospital": "Hindu Rao Hospital, Sabzi Mandi",
        "city": "Delhi",
        "latitude": 28.6695,
        "longitude": 77.2091,
        "verified": True,
        "degrees": ["MBBS", "MS ENT", "DNB"],
        "languages": ["Hindi", "English"],
        "about": "ENT surgeon with 22 years of experience in FESS, tympanoplasty, and cochlear implants.",
        "availability": {"tue": ["09:00", "10:00", "11:00"], "thu": ["09:00", "10:00"], "sat": ["10:00", "11:00"]},
    },
    {
        "id": "doc-011",
        "name": "Dr. Kavita Rao",
        "specialization": "General Physician",
        "subspecialties": ["Preventive Medicine", "Lifestyle Disease", "Geriatrics"],
        "experience_years": 9,
        "rating": 4.7,
        "review_count": 512,
        "consultation_fee": 500,
        "mode": "both",
        "hospital": "Healing Touch Clinic, Connaught Place",
        "city": "Delhi",
        "latitude": 28.6315,
        "longitude": 77.2167,
        "verified": False,
        "degrees": ["MBBS", "PGDM"],
        "languages": ["Hindi", "English", "Telugu"],
        "about": "Family physician providing comprehensive primary care for all ages with a focus on preventive health.",
        "availability": {"mon": ["10:00", "11:00", "12:00", "17:00"], "tue": ["10:00", "11:00"], "wed": ["17:00", "18:00"], "fri": ["10:00", "11:00"]},
    },
    {
        "id": "doc-012",
        "name": "Dr. Pankaj Tiwari",
        "specialization": "Neurosurgeon",
        "subspecialties": ["Brain Tumor", "Spinal Disc", "Cerebrovascular Surgery"],
        "experience_years": 17,
        "rating": 4.9,
        "review_count": 178,
        "consultation_fee": 2000,
        "mode": "offline",
        "hospital": "AIIMS Delhi, Ansari Nagar",
        "city": "Delhi",
        "latitude": 28.5678,
        "longitude": 77.2100,
        "verified": True,
        "degrees": ["MBBS", "MS Surgery", "MCh Neurosurgery", "FNS"],
        "languages": ["Hindi", "English"],
        "about": "Neurosurgeon at AIIMS with expertise in brain tumour resection, DBS, and minimally invasive spine surgery.",
        "availability": {"tue": ["08:00", "09:00"], "thu": ["08:00", "09:00"], "sat": ["08:00", "09:00", "10:00"]},
    },
    {
        "id": "doc-013",
        "name": "Dr. Aisha Khan",
        "specialization": "Neurologist",
        "subspecialties": ["Dementia", "Parkinson's Disease", "Movement Disorders"],
        "experience_years": 11,
        "rating": 4.7,
        "review_count": 243,
        "consultation_fee": 1100,
        "mode": "both",
        "hospital": "Medanta The Medicity, Gurugram",
        "city": "Gurugram",
        "latitude": 28.4441,
        "longitude": 77.0428,
        "verified": True,
        "degrees": ["MBBS", "MD Neurology", "DM", "FAAN"],
        "languages": ["Hindi", "English", "Urdu"],
        "about": "Neurologist specialising in Parkinson's disease and cognitive neurology with an integrative approach.",
        "availability": {"mon": ["11:00", "12:00", "15:00"], "wed": ["11:00", "12:00"], "fri": ["15:00", "16:00"]},
    },
    {
        "id": "doc-014",
        "name": "Dr. Sameer Khanna",
        "specialization": "Cardiologist",
        "subspecialties": ["Preventive Cardiology", "Nuclear Cardiology", "Lipid Disorders"],
        "experience_years": 19,
        "rating": 4.8,
        "review_count": 388,
        "consultation_fee": 1400,
        "mode": "both",
        "hospital": "Escorts Heart Institute, Okhla",
        "city": "Delhi",
        "latitude": 28.5440,
        "longitude": 77.2696,
        "verified": True,
        "degrees": ["MBBS", "MD Cardiology", "DM", "FACC"],
        "languages": ["Hindi", "English"],
        "about": "Preventive cardiologist focused on reducing cardiovascular risk through advanced diagnostics.",
        "availability": {"mon": ["09:00", "10:00"], "wed": ["09:00", "10:00", "11:00"], "sat": ["09:00", "10:00"]},
    },
    {
        "id": "doc-015",
        "name": "Dr. Deepa Nair",
        "specialization": "Rheumatologist",
        "subspecialties": ["Rheumatoid Arthritis", "Lupus", "Ankylosing Spondylitis"],
        "experience_years": 13,
        "rating": 4.7,
        "review_count": 201,
        "consultation_fee": 1200,
        "mode": "both",
        "hospital": "RML Hospital, Connaught Place",
        "city": "Delhi",
        "latitude": 28.6274,
        "longitude": 77.2078,
        "verified": True,
        "degrees": ["MBBS", "MD Medicine", "DM Rheumatology"],
        "languages": ["Hindi", "English", "Malayalam"],
        "about": "Rheumatologist treating autoimmune joint and connective tissue diseases with biologic therapies.",
        "availability": {"tue": ["12:00", "13:00", "16:00"], "thu": ["12:00", "13:00"], "sat": ["10:00", "11:00"]},
    },
    {
        "id": "doc-016",
        "name": "Dr. Harish Malhotra",
        "specialization": "Nephrologist",
        "subspecialties": ["Chronic Kidney Disease", "Dialysis", "Kidney Transplant"],
        "experience_years": 16,
        "rating": 4.6,
        "review_count": 167,
        "consultation_fee": 1300,
        "mode": "offline",
        "hospital": "Safdarjung Hospital, Ring Road",
        "city": "Delhi",
        "latitude": 28.5681,
        "longitude": 77.2030,
        "verified": True,
        "degrees": ["MBBS", "MD Nephrology", "DM"],
        "languages": ["Hindi", "English"],
        "about": "Nephrologist managing renal diseases with expertise in haemodialysis and transplant follow-up.",
        "availability": {"mon": ["08:00", "09:00", "10:00"], "thu": ["08:00", "09:00"], "fri": ["08:00", "09:00"]},
    },
    {
        "id": "doc-017",
        "name": "Dr. Pooja Saxena",
        "specialization": "Dermatologist",
        "subspecialties": ["Vitiligo", "Skin Cancer", "Laser Dermatology"],
        "experience_years": 8,
        "rating": 4.5,
        "review_count": 144,
        "consultation_fee": 700,
        "mode": "both",
        "hospital": "DermaPlus Clinic, Noida Sector 18",
        "city": "Noida",
        "latitude": 28.5705,
        "longitude": 77.3219,
        "verified": False,
        "degrees": ["MBBS", "MD Dermatology"],
        "languages": ["Hindi", "English"],
        "about": "Dermatologist with expertise in laser treatments, vitiligo, and early skin cancer detection.",
        "availability": {"mon": ["14:00", "15:00", "16:00"], "wed": ["14:00", "15:00"], "sat": ["11:00", "12:00"]},
    },
    {
        "id": "doc-018",
        "name": "Dr. Vivek Pandey",
        "specialization": "Orthopedist",
        "subspecialties": ["Knee Arthroscopy", "Paediatric Orthopaedics", "Trauma"],
        "experience_years": 12,
        "rating": 4.6,
        "review_count": 312,
        "consultation_fee": 900,
        "mode": "both",
        "hospital": "Columbia Asia Hospital, Gurugram",
        "city": "Gurugram",
        "latitude": 28.4946,
        "longitude": 77.0929,
        "verified": True,
        "degrees": ["MBBS", "MS Orthopaedics", "Fellowship Arthroscopy"],
        "languages": ["Hindi", "English"],
        "about": "Sports medicine orthopaedic surgeon, specialising in arthroscopic knee and shoulder surgeries.",
        "availability": {"tue": ["10:00", "11:00", "12:00"], "thu": ["10:00", "11:00"], "sat": ["09:00", "10:00"]},
    },
    {
        "id": "doc-019",
        "name": "Dr. Renu Aggarwal",
        "specialization": "Endocrinologist",
        "subspecialties": ["Thyroid Cancer", "PCOS", "Adrenal Disorders"],
        "experience_years": 14,
        "rating": 4.7,
        "review_count": 288,
        "consultation_fee": 1100,
        "mode": "both",
        "hospital": "Park Hospital, Gurugram",
        "city": "Gurugram",
        "latitude": 28.4560,
        "longitude": 77.0200,
        "verified": True,
        "degrees": ["MBBS", "MD Endocrinology", "MRCP"],
        "languages": ["Hindi", "English"],
        "about": "Endocrinologist with a special interest in thyroid malignancy and PCOS management.",
        "availability": {"mon": ["15:00", "16:00", "17:00"], "wed": ["15:00", "16:00"], "fri": ["15:00", "16:00"]},
    },
    {
        "id": "doc-020",
        "name": "Dr. Ajay Chaudhary",
        "specialization": "Pulmonologist",
        "subspecialties": ["Lung Cancer", "Interstitial Lung Disease", "Critical Care"],
        "experience_years": 21,
        "rating": 4.8,
        "review_count": 199,
        "consultation_fee": 1400,
        "mode": "offline",
        "hospital": "ILBS Hospital, Vasant Kunj",
        "city": "Delhi",
        "latitude": 28.5206,
        "longitude": 77.1562,
        "verified": True,
        "degrees": ["MBBS", "MD Respiratory Medicine", "FCCP"],
        "languages": ["Hindi", "English"],
        "about": "Pulmonologist specialising in advanced lung disease, interventional bronchoscopy, and pleural procedures.",
        "availability": {"wed": ["08:00", "09:00", "10:00"], "fri": ["08:00", "09:00"], "sat": ["08:00", "09:00"]},
    },
    {
        "id": "doc-021",
        "name": "Dr. Radhika Menon",
        "specialization": "Psychiatrist",
        "subspecialties": ["Child Psychiatry", "ADHD", "Autism Spectrum"],
        "experience_years": 9,
        "rating": 4.8,
        "review_count": 156,
        "consultation_fee": 1600,
        "mode": "both",
        "hospital": "Manas Clinic, Greater Kailash",
        "city": "Delhi",
        "latitude": 28.5442,
        "longitude": 77.2441,
        "verified": True,
        "degrees": ["MBBS", "MD Psychiatry", "Fellowship Child & Adolescent Psychiatry"],
        "languages": ["Hindi", "English", "Malayalam"],
        "about": "Child and adolescent psychiatrist with expertise in ADHD, ASD, and paediatric mood disorders.",
        "availability": {"tue": ["15:00", "16:00", "17:00"], "thu": ["15:00", "16:00"], "sat": ["11:00", "12:00"]},
    },
    {
        "id": "doc-022",
        "name": "Dr. Sanjay Mittal",
        "specialization": "Gastroenterologist",
        "subspecialties": ["Hepatology", "GI Oncology", "Capsule Endoscopy"],
        "experience_years": 18,
        "rating": 4.7,
        "review_count": 302,
        "consultation_fee": 1200,
        "mode": "offline",
        "hospital": "Pushpawati Singhania Hospital, Sheikh Sarai",
        "city": "Delhi",
        "latitude": 28.5346,
        "longitude": 77.2145,
        "verified": True,
        "degrees": ["MBBS", "MD Gastroenterology", "DM"],
        "languages": ["Hindi", "English"],
        "about": "Senior gastroenterologist with expertise in hepatology and GI cancer management.",
        "availability": {"mon": ["11:00", "12:00"], "wed": ["11:00", "12:00", "13:00"], "fri": ["11:00", "12:00"]},
    },
    {
        "id": "doc-023",
        "name": "Dr. Tanya Gill",
        "specialization": "General Physician",
        "subspecialties": ["Travel Medicine", "Infectious Disease", "Occupational Health"],
        "experience_years": 7,
        "rating": 4.6,
        "review_count": 398,
        "consultation_fee": 450,
        "mode": "both",
        "hospital": "WellCure Clinic, Dwarka",
        "city": "Delhi",
        "latitude": 28.5921,
        "longitude": 77.0460,
        "verified": False,
        "degrees": ["MBBS", "DTMH"],
        "languages": ["Hindi", "English", "Punjabi"],
        "about": "General physician providing holistic primary care with expertise in infection and travel medicine.",
        "availability": {"mon": ["09:00", "10:00", "11:00", "18:00"], "tue": ["09:00", "10:00"], "thu": ["18:00", "19:00"], "sat": ["09:00", "10:00", "11:00"]},
    },
    {
        "id": "doc-024",
        "name": "Dr. Mohan Lal Gupta",
        "specialization": "Cardiologist",
        "subspecialties": ["Paediatric Cardiology", "Congenital Heart Disease", "Echocardiography"],
        "experience_years": 25,
        "rating": 4.9,
        "review_count": 467,
        "consultation_fee": 1800,
        "mode": "offline",
        "hospital": "Lady Hardinge Medical College, New Delhi",
        "city": "Delhi",
        "latitude": 28.6353,
        "longitude": 77.2099,
        "verified": True,
        "degrees": ["MBBS", "MD Paediatrics", "DM Cardiology", "FICC"],
        "languages": ["Hindi", "English"],
        "about": "Paediatric cardiologist with 25 years treating complex congenital heart defects in children.",
        "availability": {"mon": ["08:00", "09:00"], "wed": ["08:00", "09:00", "10:00"], "fri": ["08:00", "09:00"]},
    },
    {
        "id": "doc-025",
        "name": "Dr. Shweta Dubey",
        "specialization": "Neurologist",
        "subspecialties": ["Multiple Sclerosis", "Neuroimmunology", "Headache"],
        "experience_years": 10,
        "rating": 4.7,
        "review_count": 178,
        "consultation_fee": 1000,
        "mode": "both",
        "hospital": "Yashoda Hospital, Kaushambi, Ghaziabad",
        "city": "Noida",
        "latitude": 28.6467,
        "longitude": 77.3236,
        "verified": True,
        "degrees": ["MBBS", "MD Neurology", "DM"],
        "languages": ["Hindi", "English"],
        "about": "Neurologist focused on MS, autoimmune neurology, and complex headache disorders.",
        "availability": {"tue": ["11:00", "12:00", "13:00"], "thu": ["11:00", "12:00"], "sat": ["10:00", "11:00", "12:00"]},
    },
    {
        "id": "doc-026",
        "name": "Dr. Abhishek Roy",
        "specialization": "Urologist",
        "subspecialties": ["Kidney Stones", "Prostate Cancer", "Minimally Invasive Urology"],
        "experience_years": 14,
        "rating": 4.7,
        "review_count": 223,
        "consultation_fee": 1000,
        "mode": "both",
        "hospital": "Venkateshwar Hospital, Dwarka",
        "city": "Delhi",
        "latitude": 28.5773,
        "longitude": 77.0553,
        "verified": True,
        "degrees": ["MBBS", "MS Surgery", "MCh Urology"],
        "languages": ["Hindi", "English", "Bengali"],
        "about": "Urologist performing RIRS and PCNL for kidney stones and laparoscopic prostate surgeries.",
        "availability": {"mon": ["12:00", "13:00"], "wed": ["12:00", "13:00", "14:00"], "fri": ["12:00", "13:00"]},
    },
    {
        "id": "doc-027",
        "name": "Dr. Neha Srivastava",
        "specialization": "Ophthalmologist",
        "subspecialties": ["Lasik Surgery", "Cornea", "Dry Eye"],
        "experience_years": 11,
        "rating": 4.6,
        "review_count": 198,
        "consultation_fee": 600,
        "mode": "both",
        "hospital": "Sharp Sight Eye Hospital, Pitampura",
        "city": "Delhi",
        "latitude": 28.7042,
        "longitude": 77.1313,
        "verified": False,
        "degrees": ["MBBS", "MS Ophthalmology", "FICO"],
        "languages": ["Hindi", "English"],
        "about": "Eye specialist performing LASIK and advanced corneal procedures with state-of-the-art equipment.",
        "availability": {"tue": ["10:00", "11:00", "12:00"], "thu": ["10:00", "11:00"], "sat": ["10:00", "11:00"]},
    },
    {
        "id": "doc-028",
        "name": "Dr. Gaurav Bhatt",
        "specialization": "ENT Specialist",
        "subspecialties": ["Cochlear Implant", "Snoring & Sleep Apnea", "Voice Disorders"],
        "experience_years": 16,
        "rating": 4.8,
        "review_count": 244,
        "consultation_fee": 900,
        "mode": "both",
        "hospital": "Action Cancer Hospital, Paschim Vihar",
        "city": "Delhi",
        "latitude": 28.6609,
        "longitude": 77.1018,
        "verified": True,
        "degrees": ["MBBS", "MS ENT", "FRCS Edinburgh"],
        "languages": ["Hindi", "English"],
        "about": "ENT surgeon specialised in cochlear implants, sleep surgery, and voice rehabilitation.",
        "availability": {"mon": ["14:00", "15:00", "16:00"], "wed": ["14:00", "15:00"], "sat": ["09:00", "10:00", "11:00"]},
    },
    {
        "id": "doc-029",
        "name": "Dr. Ishaan Khatri",
        "specialization": "Rheumatologist",
        "subspecialties": ["Gout", "Osteoporosis", "Sjogren Syndrome"],
        "experience_years": 9,
        "rating": 4.5,
        "review_count": 134,
        "consultation_fee": 1000,
        "mode": "online",
        "hospital": "Online Consultations (HealthConnect Platform)",
        "city": "Delhi",
        "latitude": 28.6139,
        "longitude": 77.2090,
        "verified": True,
        "degrees": ["MBBS", "MD Rheumatology"],
        "languages": ["Hindi", "English"],
        "about": "Rheumatologist offering online consultations for autoimmune arthritis, gout, and bone health.",
        "availability": {"mon": ["18:00", "19:00", "20:00"], "tue": ["18:00", "19:00"], "wed": ["18:00", "19:00", "20:00"], "fri": ["18:00", "19:00"]},
    },
    {
        "id": "doc-030",
        "name": "Dr. Lata Krishnamurthy",
        "specialization": "Neurologist",
        "subspecialties": ["Peripheral Neuropathy", "Neuromuscular Disease", "Botox Therapy"],
        "experience_years": 20,
        "rating": 4.9,
        "review_count": 356,
        "consultation_fee": 1600,
        "mode": "both",
        "hospital": "National Brain Research Centre Affiliated, Manesar",
        "city": "Gurugram",
        "latitude": 28.3669,
        "longitude": 76.9913,
        "verified": True,
        "degrees": ["MBBS", "MD Neurology", "DM", "PhD Neuroscience"],
        "languages": ["Hindi", "English", "Tamil", "Kannada"],
        "about": "Senior neurologist and neuroscientist with extensive expertise in neuromuscular disease and neuropathy.",
        "availability": {"mon": ["10:00", "11:00"], "wed": ["10:00", "11:00", "12:00"], "fri": ["10:00", "11:00"]},
    },
]


async def seed_doctors_if_empty(db) -> None:
    """Insert all seed doctors if the doctors table is empty."""
    async with db.execute("SELECT COUNT(*) FROM doctors") as cur:
        row = await cur.fetchone()
        count = row[0] if row else 0
    if count > 0:
        return
    for doc in DOCTORS_SEED:
        await db.execute(
            """INSERT INTO doctors
               (id, name, specialization, subspecialties, experience_years,
                rating, review_count, consultation_fee, mode, hospital, city,
                latitude, longitude, availability, verified, degrees, languages, about)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (
                doc["id"], doc["name"], doc["specialization"],
                json.dumps(doc["subspecialties"]), doc["experience_years"],
                doc["rating"], doc["review_count"], doc["consultation_fee"],
                doc["mode"], doc["hospital"], doc["city"],
                doc["latitude"], doc["longitude"],
                json.dumps(doc["availability"]), 1 if doc["verified"] else 0,
                json.dumps(doc["degrees"]), json.dumps(doc["languages"]),
                doc["about"],
            ),
        )
    await db.commit()
